### ISSUE TITLE
Improve `electron` support

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/http-timer#11]
Currently the timings look this:

```js
  timings: {
    start: 1576269343669,
    socket: undefined,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: 1576269343682,
    response: 1576269344083,
    end: undefined,
    error: undefined,
    phases: {
      wait: undefined,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: NaN,
      firstByte: 401,
      download: undefined,
      total: undefined
    }
  }
```

Missing:

- `timings.end`
- `timings.phases.request`
- `timings.phases.download`
- `timings.phases.total`

**Comment by sindresorhus** [comment]
If you add any workarounds, ensure you also open Electron issues.

**Comment by szmarczak** [comment]
They ain't welcome: https://github.com/electron/electron/issues/21517 https://github.com/electron/electron/issues/11787#issuecomment-565624923

https://github.com/electron/electron/issues/11787 was fixed by https://github.com/electron/electron/pull/21244 but there's no mention of it. The person who handled it, even didn't care to check if the issue is real though there was reproducible code provided. It's like "you know, we are aware of the issue, we are able to fix it, but we won't because there are dumb people like you that are gonna fix it". I just feel this way.

For example they say ["follow the Code of Conduct"](https://github.com/electron/electron/issues/11787#issuecomment-565624923) but they [don't follow it either](https://github.com/electron/electron/pull/21244#issuecomment-558882497).

I just posted [this](https://user-images.githubusercontent.com/36894700/70836357-31a5bc80-1e00-11ea-9dc7-353132d6eb10.png) (instead of `make` I meant `mark`).
