### ISSUE TITLE
Missing `'aborted'` listener

### ISSUE THREAD

**Issue by ronag** [szmarczak/http-timer#20]
The `IncomingMessage` response object does not emit `ECONNRESET` as an `'error'`, rather it emits an `'aborted'` event. http-timer should probably listen to the `'aborted'` handler and treat it as an error?

**Comment by ronag** [comment]
Some related reading if interested:

https://github.com/nodejs/node/issues/28172
https://github.com/nodejs/node/pull/28677

**Comment by szmarczak** [comment]
Fixed in `4.0.6`
