### ISSUE TITLE
errorMonitor' is not exported by __vite-browser-external:events

### ISSUE THREAD

**Issue by pigping88** [szmarczak/http-timer#31]
errorMonitor' is not exported by __vite-browser-external:events, imported by node_modules/@szmarczak/http-timer/dist/source/index.js
import { errorMonitor } from 'events';

**Comment by adamreisnz** [comment]
is there any explanation here?
I'm running a site deploy on Netlify and running into this error (running on Node 22):

```
1:47:26 PM: [error] [nitro] RollupError: node_modules/@szmarczak/http-timer/dist/source/index.js (1:9): "errorMonitor" is not exported by "node_modules/unenv/runtime/node/events/index.mjs", imported by "node_modules/@szmarczak/http-timer/dist/source/index.js".
1:47:26 PM: 1: import { errorMonitor } from 'events';
1:47:26 PM:             ^
```
