### ISSUE TITLE
File not found error on all versions

### ISSUE THREAD

**Issue by ghost** [szmarczak/http-timer#4]
npm i @szmarczak/http-timer or npm i http-timer are returning 404 errors.

**Comment by sindresorhus** [comment]
It's `npm install @szmarczak/http-timer` and it works fine for me. This is probably an issue with npm or you system.

**Comment by sindresorhus** [comment]
@szmarczak You should document the install line (`npm install @szmarczak/http-timer`) in the readme.

**Comment by ghost** [comment]
`npm i `is shorthand for `npm install` Very odd.. this is the only package giving me a 404 and i've been installing hundreds over the past few days without issue. Will investigate my config if you're positive this is ok for you on a fresh install. thanks for the feedback :)

**Comment by ghost** [comment]
Weird config issue. Reset npmrc file at root and started working. Sorry for raising this.

**Comment by szmarczak** [comment]
@sindresorhus Done :)

@edanedison No problem! We're happy to help.
